Dev
asg475/formacion pull request #2
Opened 2024-10-14 07:29 UTC by asg475

Solamente es el archivo objetos.py, ya que no lo sobrescribí sobre el otro.

Se ha creado utilizando OOP, una Api que te permite crear botones, hacer modificaciones sobre ellos, borrarlos y leer su contenido.

2024-10-14 08:26 UTC, pecasruiz requested changes
Cambia las cosas que te he pedido, por lo demas mejor pinta que antes. La descripcion me sigue pareciendo algo pobre. Me falta que me expliques como levantarlo para hacer peticiones a tu API y ver si funciona

2024-10-14 08:26 UTC, pecasruiz commented on objetos.py
> +    id_previa = 1
Aqui pondria un cero, porque sino el primer boton tendra id=2

2024-10-14 08:26 UTC, pecasruiz commented on objetos.py
> +def crear_boton(nombre: str, color: str):
que pasa si meto mal el color?

2024-10-14 08:26 UTC, pecasruiz commented on objetos.py
> +@app.post("/Botones")
las rutas para hacer peticiones van en minusculo

2024-10-14 08:26 UTC, pecasruiz commented on objetos.py
> +    for boton in Boton.lista_de_botones:
Esto se podria mejorar, en vez usar una lista prueba a hacerlo con diccionarios, donde la clave sea el id y luego tenga como valores el nombre, color...

2024-10-14 08:26 UTC, pecasruiz commented on objetos.py
> +    for boton in Boton.lista_de_botones:
lo mismo

2024-10-15 06:22 UTC, pecasruiz commented on objetos.py
> +    id_previa = 1
He probado a levantar el sistema y ya empieza por 1

2024-10-15 06:26 UTC, asg475 commented on objetos.py
> +def crear_boton(nombre: str, color: str):
esto la verdad es que metiendo el color como un string no se me ocurre manera para comprobarlo

2024-10-15 06:27 UTC, asg475 commented on objetos.py
> +@app.post("/Botones")
Ya están todas las rutas en minúscula, lo único que queda en mayúscula es el nombre de la clase

2024-10-15 06:29 UTC, asg475 commented on objetos.py
> +    for boton in Boton.lista_de_botones:
esto lo he dejado como esta ya que el enunciado pedia que los botones se fuesen guardando en una lista y que a la funcion le dieses como input el nombre del boton

2024-10-15 06:29 UTC, asg475 commented on objetos.py
> +    for boton in Boton.lista_de_botones:
corregido tambien

2024-10-15 06:33 UTC, asg475 commented
Para lanzar el programa desde la terminal del visual code he usado el siguiente comando:
fastapi dev objetos.py --host 0.0.0.0 --port 8000
y para comprobar que funcionase desde el buscador he puesto:
localhost:8000/docs

2024-10-15 06:43 UTC, pecasruiz commented on objetos.py
> +@app.post("/Botones")
perfecto

2024-10-15 06:43 UTC, pecasruiz commented on objetos.py
> +    for boton in Boton.lista_de_botones:
ok

2024-10-15 07:06 UTC, pecasruiz requested changes
Haz ese ultimo cambio y pasamos la PR!

2024-10-15 07:06 UTC, pecasruiz commented on objetos.py
> +def crear_boton(nombre: str, color: str):
Por ejemplo comprobando que empieza por # y que tiene 6 caracteres

2024-10-15 07:24 UTC, asg475 commented on objetos.py
> +def crear_boton(nombre: str, color: str):
ya esta hecho

2024-10-17 06:43 UTC, closed without merging

2024-10-17 06:44 UTC, asg475 commented
cierro esta para abrir una nueva